import { useLayoutEffect } from 'react';
import cover from '../../tt2.jpeg';

function TimeTravel() {

    useLayoutEffect(() => {
        window.scrollTo(0, 0)
    });

    return (
        <div>
            <img className="coverPhoto" src={cover} />
            <div className="centeredTitleB">Time Travel</div>
            <div className="backgroundContainer">
                <div className="backgroundItem">
                    <h3 className="backgroundTitle">Description</h3>
                    <p className="backgroundDescription">
                        Time travel is often thought of as a fictional or fake phenomenon, yet it is a subject that scholars, philosophers, and physicists truly consider. That is not to say that time travel is entirely possible, but there is much to consider within the subject. Here we outline some of the central ideas and features regarding time travel.
                    </p>
                    <p className="backgroundDescription">
                        First, we must recognize that there are three kinds of time travel. The first is Wellsian Time Travel. In this type of time travel, we see funny worldlines. For instance, we might see broken worldlines in which a time traveler maintains a normal worldline up until the point at which he time travels. Then, his worldline stops and reappears in previous hyperplanes, then continuing from that new point. When visualizing or drawing this broken worldline, context is important, for the above described situation may appear as if a person of age X just appears at some point and dies some time later. Then, a baby is born some time later and somehow disappears––at the time when the time traveler travels––and this person who disappeared somehow looks the same as the person who randomly appeared in the past. An example of this type of time travel would be the film <i>Back to the Future</i>. Another example of funny worldlines in Wellsian Time Travel is zig-zag time travel. In this case, the worldline would be continuous and would zig-zag into the past or future. When zigging backwards, the time traveler is aging backwards in time while everyone is aging properly. At certain hyperplanes, there would be two versions of the time traveler, one experiencing regular time and one moving backwards in time. At the turning point in which these two versions meet, they would converge and annihilate each other. An example of this is present in <i>Harry Potter</i> when Harry and Hermione travel to the past.
                    </p>
                    <p className="backgroundDescription">
                        The second type of time travel is Relativistic Time Travel, in which we see funny physics at play. The interesting thing about this time travel is that it is 100% physically possible as demonstrated by special relativity. When the time traveler travels, he leaves behind his starting point and experiences a certain amount of time as he travels. When he returns, a different amount of time has passed for those at his original starting point whereas he has experienced less time. This occurs and is possible because as shown through special relativity, time dilation is a real phenomenon. Traveling close to the speed of light, for example, would allow for one to experience a different amount of time than another observer who is moving relatively slower as we saw in the example of time dilation under Minkowski spacetime. It is important to note that while physically possible, Relativistic Time Travel only allows for traveling to the future. An example of this would be the movie <i>Interstellar</i>, when two travelers visit a planet near a blackhole, spending all of an hour on this planet. When they return to their spaceship, their partner has experienced twenty years.
                    </p>
                    <p className="backgroundDescription">
                        The final type of time travel is Closed Timelike Curve (CTC) Time Travel. Every piece of matter experiences a timelike curve that threads lightcones, and these timelike curves can be closed: Imagine a straight worldline on a piece of paper; fold that paper so that the top of the worldline is glued to the bottom of the worldline, creating a cylinder out of the paper. This closed structure allows traveling to the past as the worldline would reach its prior line. Another variation of CTC time travel would be wormhole spacetime, in which there exists two slits that represent the same hyperplane. When someone enters one of these slits, they come out of the other.
                    </p>
                    <p className="backgroundDescription">
                        These are the three types of time travel. Note that the first, Wellsian Time Travel, is fictional, whereas the second two types are physics-based.
                    </p>
                    <p className="backgroundDescription">
                        Now, we beg the main question, is time travel possible? This is a loaded question. First of all, ‘possible’ is a modal term, meaning we need to clarify in what sense we are gauging possibility. It is clear that currently, we have yet to develop technology advanced enough to allow us to time travel, thereby making time travel technologically impossible. Thus, we answer this question in terms of logical possibility. That is, if time travel were physically and technologically feasible, would it be logically possible?
                    </p>
                    <p className="backgroundDescription">
                        Before turning to this question, we must note some important points about time travel. First, things that never happened can’t happen. In other words, you can’t change past things. Time traveling is somewhat like watching a movie where the ending scene is shown at the beginning. We know what happens and thus what will happen. In the movie <i>Saving Private Ryan</i>, for instance, the audience is shown a snippet at the beginning of the movie of future Private Ryan, meaning throughout the film, we know he does not die. Time travel is the same: one cannot change the past. Secondly, time travelers maintain the same freedom as they did during the time which they travel to. For instance, if I were to time travel to the past when I was in the 5th grade, I would maintain the same freedom as when I first experienced the 5th grade. This is a difficult idea to grasp, for it seems to lead to a contradiction of maintaining the same freedom yet not being able to change the past. Let me explain through an example. If I were to time travel to my 5th grade self, whatever I do during that period would also have occurred while I was experiencing 5th grade for the first time. If I, as a time traveler, were to wave to my 5th grade self, I, when I was a 5th grader, would have seen older me wave to me. Additionally, the 5th grade self I waved to as a time traveler would proceed to time travel as well, and this loop would continue to ensue.
                    </p>
                    <p className="backgroundDescription">
                        Furthermore, we have developed an adequate understanding of the background and context behind time travel to now turn to the question of logical possibility. The following argument, the grandfather paradox, provides an assessment to answer this question.
                    </p>
                </div>

                <div className="backgroundItem">
                    <h3 className="backgroundTitle">The Grandfather Paradox</h3>
                    <div className="premiseContainer">
                        <p className="premise">
                            <b>Premise 1:</b> If time travel is possible, then a person can prevent their own birth.
                        </p>
                        <p className="premise">
                            <b>Premise 2:</b> No one can prevent their own birth.
                        </p>
                        <p className="premise">
                            <b>Conclusion:</b> Therefore, time travel is not possible.
                        </p>

                        <br></br>

                        <p className="premise">
                            <b>Justification for Premise 1:</b> Premise 1 holds that if time travel is possible, then a person can prevent their own birth, which is implicitly done by killing their grandfather. Consider person X, who hates his grandfather. Unfortunately, X’s grandfather has already passed, yet X maintains his hatred for his grandfather. Thus, he builds a time machine, making time travel physically possible, and prepares himself in all the right ways: he plans the exact time, the perfect location, assembles his perfectly working rifle, trains to be the next American Sniper, and still maintains his hatred and thus his intentions to kill his grandfather. X hops into his time traveling device and is lined up with all the right circumstances to complete the murder. In this sense, person X can kill his grandfather, which would prevent X’s own birth. Because X has all the right circumstances––place, time, tool, skill, intention––X has the ability to complete the killing. Even if X somehow failed––a bird suddenly flew into the shot––or X chickened out at the last minute, X nonetheless maintained the ability to do it. Therefore, in other words, X can kill his grandfather and consequently, can prevent his own birth.
                        </p>
                        <p className="premise">
                            <b>Justification for Premise 2:</b> Premise 2 holds that no one can prevent their own birth. It is impossible because it is a self-defeating act such that performing the act entails a failure to perform the act. We can see this by considering again person X traveling to the past to kill his grandfather. Let us say he succeeds and kills his grandfather. In this case, X’s grandfather never lives to meet his wife, X’s grandmother. Then, this would mean one of X’s parents, the child of X’s grandparents, is never born. If one of X’s parents is never born, then X is never born. Then X does not exist. But he does because X traveled to the past to kill his grandfather. Here arises the issue: If X prevents his own birth, then he does not prevent his own birth because he does not exist. Therefore, it follows that no one can prevent their own birth.
                        </p>

                        <br></br>

                        <p className="premise">
                            <b>Evaluation:</b> I argue that the grandfather paradox is unsound because of Lewis’ solution.
                        </p>
                        <p className="premise">
                            In response to the grandfather paradox, Lewis claims the argument is unsound because it is logically invalid. The reason behind this, he claims, is that the word ‘can’ is context-dependent, and its usage in premise 1 and 2 are different from one another. One way to see this is by considering a concert pianist who is currently in jail. In one sense, the pianist can play piano––and very well at that if he plays at concerts––and this is a perfectly understandable sense in which the pianist can play piano. However, if you consider the fact that the pianist is in jail and therefore does not have the access or freedom to play piano, then that is another perfectly understandable sense in which he cannot play piano.
                        </p>
                        <p className="premise">
                            In the case of the grandfather paradox, Lewis claims, a similar phenomenon arises where there is a sense in which the time traveler can kill his grandfather: all the circumstances––time, place, skills, tools, intentions––align, providing the traveler with the ability to kill his grandfather. We must note here, however, that Lewis incites the requirement on behalf of the traveler of ignoring the fact that the person being killed is his grandfather. The reason for this is that once it is introduced as fact that the person being killed is the traveler’s grandfather, the scope of facts changes. With this additional grandfather fact, the ability is then negated since that fact draws in the ideas cited in premise 2, in which one cannot kill his grandfather since it is a self-defeating act. Now regarding premise 2, again, there is another perfectly understandable sense in which the traveler cannot kill his grandfather because, as mentioned, it is a self-defeating act. Furthermore, Lewis demonstrates that there are two perfectly understandable senses in which the time traveler both can and cannot kill his grandfather, highlighting an inconsistency in the word ‘can’. This, he claims, is the reason the argument is logically invalid and therefore unsound.
                        </p>
                        <p className="premise">
                            Vivehlin agrees with Lewis that the argument is unsound but disagrees with Lewis’ solution to the argument. Instead, she holds that premise 1 is false. The reason behind this stems from her own definition of the word ‘can’. She claims that whether something ‘can’ happen is instead determined by a condition, known as Vivehlin’s Rule, which claims that X can A only if, were X to try to A, there is at least a chance it might succeed. In the case of the grandfather paradox, she argues, it seems even if the traveler were to attempt multiple times to kill his grandfather, he would fail every time. She introduces the notion of considering alternative possible worlds as a way to explore possibilities of success. That is, since Vivehlin’s condition is a counterfactual condition, considering alternative possible worlds with different outcomes is a way of seeing whether any such world has an outcome in which the traveler does indeed kill his grandfather. These alternative worlds, however, must be similar to ours. She discusses the possible world in which the traveler does indeed kill his grandfather, but his grandfather resurrects to avoid the implications of a self-defeating act. This, Vivehlin claims, is too far off and weird a world to truly consider, and instead, we must limit ourselves to worlds that are similar to our actual world. This naturally instigates the question of how to determine whether an alternative possible world is similar enough to our actual world. In response, Vivehlin claims it is context dependent, using the same logic as Lewis’ solution to the word ‘can’. Furthermore, she also reaches the conclusion that the argument is unsound because there is no alternate possible world similar enough to ours in which someone can kill their own grandfather, meaning there is no chance that someone can prevent their own birth. Thus, premise 1 is rejected and the argument is unsound.
                        </p>
                        <p className="premise">
                            I disagree with Vivehlin’s argument. She arrives at a similar conclusion to Lewis in that the matter of ability is context dependent. However, her context-dependence is based on alternate possible worlds, of which there are infinite possibilities. Even if we limit our consideration to possible worlds that are similar enough to ours, it is arguable that attempting to limit all alternate possible worlds to just those that are similar enough to our actual world is futile. This is because according to Vivehlin, similarity is context-dependent, which maintains no criteria to definitively claim whether it is similar enough or not. In other words, how do we conclude that a world is too far off if it is based on context, which has no discrete criteria for claiming another world as similar enough to our actual world?
                        </p>
                        <p className="premise">
                            In this regard, it seems that the idea of a world being similar enough, merged with the lack of concrete judgment on sufficient context, that anything can always be considered possible. If we apply Vivehlin’s ideas to the grandfather paradox, it will always be possible that the traveler kills his grandfather because there are an infinite number of alternate possible worlds, so there must exist a world where the traveler kills his grandfather. Vivehlin’s argument to counter this is by limiting the consideration of possible worlds to only those that are similar enough to our actual world. But similar enough is context-dependent. One may say that a possible world is not similar enough and therefore come to the conclusion that the traveler cannot kill his grandfather However, there might be another who considers the world similar enough and thus the traveler can kill his grandfather. How do we ascertain whether an alternate possible world is similar enough? Collective agreement? But what if we do not agree? Then we have no basis or grounds to claim that something can or cannot happen.
                        </p>
                        <p className="premise">
                            It seems there are two issues: First, the infinite number of alternate possible worlds, and second, the inability to definitively determine whether a possible world is similar enough to ours. In a way, they are intertwined with one another. Let us lay it out in clearer terms: The ability of the traveler to kill his grandfather is determined by the possibility of success, which in turn is determined by what happens in alternate possible worlds. But whether or not these alternate possible worlds can be considered, depends on their similarity to our actual world. And this similarity is context-dependent. And this dependence on context exhibits no definitive criteria to be considered similar enough, meaning it is up to the individual to decide whether the context is sufficient to be considered similar enough. This does not sit well with me because extended beyond the grandfather paradox, it opens up anything that many would consider impossible to instead be possible. Consider whether or not I can fly. The answer should be no, I cannot fly. However, under Vivehlin’s logic, we can consider alternate possible worlds. Since there are infinite alternate possible worlds, there ought to be one in which I maintain the ability to fly. Vivehlin would say that world is too far off to consider. But using her logic, since similar enough is context dependent and there exists no collective understanding of what context would garner enough similarities to be considered similar enough, I could argue that it is similar enough. Additionally, since there are an infinite number of alternate possible worlds, there must exist a world in which I can fly and all historical events align with our actual world. Then I could argue even further that I can fly, and then it would be possible that I can fly. This can be extended to anything, and it would be possible that I can do essentially anything.
                        </p>
                        <p className="premise">
                            It seems that Vivehlin’s logic opens up anything to be possible, which stems from the vague notion and determination of whether any context is similar enough to our actual world. Since it is impossible that I can fly, and impossible that I can do a number of other things, I reject Vivehlin’s solution to the grandfather paradox, and instead agree with Lewis’ solution.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TimeTravel;